import assert from 'node:assert/strict';
import {App} from '../src/app.js';
import {COURSE,DRIVE} from '../src/config.js';
import {getUpgradeLevels,createProfile,bestKey} from '../src/progression.js';
import {GHOST_KEY,MAX_GHOSTS,MAX_GHOST_SAMPLES,MAX_GHOST_BYTES,GhostRecorder,ghostKey,createGhostStore,normalizeGhostStore,loadGhosts,saveGhosts,readGhostEnabled,saveGhostEnabled,findGhost,mergeGhostStores,storeGhost,sampleGhost} from '../src/ghost.js';
let count=0;const check=(value,message)=>{assert(value,message);count++;};
const stageIndex=COURSE.findIndex(stage=>!stage.kind),stage=COURSE[stageIndex],length=stage.lengthU*stage.laps;
const context={playerId:'player-one',stageIndex,seed:1989,laps:stage.laps,car:'falcone_f42',mode:'timetrial',difficulty:'casual',cpuDifficulty:'easy',upgrades:getUpgradeLevels(createProfile(),'falcone_f42')};
const player={id:context.playerId,name:'Alex'};
function run(seconds=120,extra={}){
  const recorder=new GhostRecorder({...context,...extra}),state={...context,...extra,status:'racing',stageTimeSec:0,racePenaltySec:0,s:0,lateral:0,headingError:0,slipAngle:0,crashSpin:0,airHeight:0,speedMph:100};
  const steps=Math.round(seconds*10);for(let i=0;i<=steps;i++){state.stageTimeSec=i/10;state.s=length*i/steps;recorder.observe(state);}
  const result={stageIndex,completed:true,won:true,laps:stage.laps,timeSec:seconds};
  return {recorder,state,result,record:recorder.finish(result,state,{...player,id:state.playerId})};
}
const base=run(),record=base.record;check(!!record,'a complete finite run produces a recording');check(record.samples.length>=590&&record.samples.length<=610,'ordinary runs sample at five Hz');check(record.samples[0][0]===0&&record.samples.at(-1)[0]===120000,'both endpoints retained');check(record.samples.every(row=>row.every(Number.isSafeInteger)),'all stored samples are quantized integers');
check(ghostKey(player.id,context)!==ghostKey('other',context),'players are isolated');
for(const [key,value] of [['seed',42],['car','viper_proto'],['difficulty','pro'],['cpuDifficulty','hard'],['stageIndex',(stageIndex+1)%COURSE.length]])check(ghostKey(player.id,context)!==ghostKey(player.id,{...context,[key]:value}),`${key} changes compatibility`);
check(ghostKey(player.id,{...context,upgrades:{engine:3}})===ghostKey(player.id,context),'upgrade builds share the car challenge');check(ghostKey(player.id,{...context,mode:'duel'})==='','rival races have no ghost key');
let store=storeGhost(createGhostStore(),record).store;check(findGhost(store,player.id,context)===store.records[0],'compatible lookup');check(!findGhost(store,'other',context),'other profile cannot see the recording');check(!storeGhost(store,record).saved,'duplicate cannot replace best');check(!storeGhost(store,run(125).record).saved,'slower result cannot replace best');const quicker=run(115).record;check(storeGhost(store,quicker).saved,'faster result can replace best');
check(!base.recorder.finish({...base.result,completed:false},base.state,player),'incomplete finish rejected');check(!base.recorder.finish(base.result,base.state,{id:'other',name:'Other'}),'wrong owner rejected');check(!base.recorder.finish(base.result,{...base.state,car:'viper_proto'},player),'changed race vehicle rejected');check(!base.recorder.finish({...base.result,laps:1},base.state,player),'missing lap rejected');check(!base.recorder.finish({...base.result,stageIndex:(stageIndex+1)%COURSE.length},base.state,player),'changed event rejected');check(!!base.recorder.finish({...base.result,won:false},base.state,player),'valid loss may be a car best');
for(const field of ['s','lateral','headingError','airHeight','speedMph','stageTimeSec','racePenaltySec']){const rec=new GhostRecorder(context);rec.observe({...base.state,stageTimeSec:0,[field]:NaN});check(rec.invalid,`non-finite ${field} invalidates recording`);}
let rec=new GhostRecorder(context),state={...base.state,s:0,stageTimeSec:0};rec.observe(state);state={...state,stageTimeSec:.01,s:length};rec.observe(state);check(rec.invalid,'impossible progress jump rejected');
rec=new GhostRecorder(context);state={...base.state,s:0,stageTimeSec:0};rec.observe(state);rec.observe({...state,paused:true,stageTimeSec:40});check(rec.samples.length===1&&!rec.invalid,'pause does not sample or advance recording');
state={...state,s:10,stageTimeSec:.2};rec.observe(state);rec.discontinuity();rec.observe({...state,stageTimeSec:.4,s:5,lateral:2});check(rec.samples.at(-1)[6]===1,'boundary reset marked as a discontinuity');
rec=new GhostRecorder(context);state={...base.state,s:0,stageTimeSec:0};rec.observe(state);rec.observe({...state,s:10,stageTimeSec:.1});rec.observe({...state,s:30,stageTimeSec:.2,racePenaltySec:8});check(rec.samples.length===3&&rec.samples[1][0]===100&&rec.samples[2][6]===1,'penalty jump preserves the preceding off-cadence position');
const gap={...record,timeSec:9,samples:[[0,0,0,31000,0,600,0],[1000,1000,100,31000,0,600,0],[8000,3000,400,-31000,100,700,1],[9000,4000,500,-30000,0,800,0]]};
check(sampleGhost(gap,4).s===10&&sampleGhost(gap,7.999).lateral===1,'penalty gap holds the earlier pose');check(sampleGhost(gap,8).s===30&&sampleGhost(gap,8).lateral===4,'penalty end snaps to the recorded position');check(sampleGhost(gap,8.5).s===35,'ordinary intervals interpolate');check(sampleGhost(gap,9.01)===null&&sampleGhost(gap,-1)===null,'ghost does not continue beyond its saved run');
const wrap={...gap,timeSec:1,samples:[[0,0,0,31000,0,0,0],[1000,100,0,-31000,0,0,0]]};check(Math.abs(sampleGhost(wrap,.5).headingError-Math.PI)<.001,'yaw interpolates over the short circular arc');const out={};check(sampleGhost(gap,.5,out)===out,'playback reuses a renderer-owned pose buffer');
const long=run(650);check(long.record&&long.record.samples.length<=MAX_GHOST_SAMPLES,'long run thins samples within the limit');check(long.record.samples.at(-1)[1]===Math.round(length*100),'thinning retains the finishing position');
// Signed speed is part of playback, so the ghost moves and spins its wheels
// backward during a real reverse segment. More than 80m before the start is a
// legal circuit coordinate; the completed recording still needs both laps.
const reverseRecorder=new GhostRecorder(context),reverseState={...base.state,s:0,stageTimeSec:0,speedMph:-DRIVE.reverseMaxMph};
const reverseSeconds=15,backwards=reverseSeconds*DRIVE.reverseMaxMph*DRIVE.mphToWorld,forwardSeconds=120,totalSeconds=reverseSeconds+forwardSeconds;
for(let i=0;i<=reverseSeconds*10;i++){reverseState.stageTimeSec=i/10;reverseState.s=-i/10*DRIVE.reverseMaxMph*DRIVE.mphToWorld;reverseRecorder.observe(reverseState);}
check(reverseState.s<-80&&!reverseRecorder.invalid,'Physical reversing beyond the old start bound remains recordable');
reverseState.speedMph=(length+backwards)/forwardSeconds/DRIVE.mphToWorld;
for(let i=1;i<=forwardSeconds*10;i++){reverseState.stageTimeSec=reverseSeconds+i/10;reverseState.s=-backwards+(length+backwards)*i/(forwardSeconds*10);reverseRecorder.observe(reverseState);}
const reversed=reverseRecorder.finish({...base.result,timeSec:totalSeconds},reverseState,player);
check(!!reversed&&reversed.samples.some(row=>row[1]<-8000&&row[5]<0),'Valid finish keeps negative positions and signed reverse speed');
check(sampleGhost(reversed,5).s<sampleGhost(reversed,4).s&&sampleGhost(reversed,5).speedMph===-DRIVE.reverseMaxMph,'Playback preserves backward travel and wheel direction');
check(normalizeGhostStore({version:1,records:[reversed]}).records.length===1,'Signed reverse recording survives normalization');
check(normalizeGhostStore({version:1,records:[record]}).records.length===1,'Legacy forward-only recordings remain compatible');
const reverseStorage=new Map(),reverseMemory={getItem:key=>reverseStorage.get(key)??null,setItem:(key,value)=>reverseStorage.set(key,value)};
check(saveGhosts({version:1,records:[reversed]},reverseMemory)&&loadGhosts(reverseMemory).records[0].samples.some(row=>row[5]<0),'Signed reverse recording survives persistence');
rec=new GhostRecorder(context);rec.observe({...base.state,s:0,stageTimeSec:0,speedMph:-DRIVE.reverseMaxMph});rec.observe({...base.state,s:-100,stageTimeSec:.01,speedMph:-DRIVE.reverseMaxMph});check(rec.invalid,'Impossible backward teleport is rejected without a reset event');
rec=new GhostRecorder(context);rec.observe({...base.state,s:0,stageTimeSec:0,speedMph:-DRIVE.reverseMaxMph});rec.discontinuity();rec.observe({...base.state,s:-100,stageTimeSec:.2,speedMph:0});check(!rec.invalid&&rec.samples.at(-1)[6]===1,'Explicit backward recovery remains a snap, not a teleport');
for(const mutate of[r=>r.samples[2][5]=-5001,r=>r.samples[2][1]=Math.floor(-(r.timeSec*DRIVE.reverseMaxMph*DRIVE.mphToWorld+80)*100)-1]){const bad=structuredClone(reversed);mutate(bad);check(normalizeGhostStore({version:1,records:[bad]}).records.length===0,'Signed samples still enforce speed and physical reverse coordinate limits');}
for(const mutate of [r=>r.layoutVersion++,r=>r.laps=1,r=>r.samples[1][0]=0,r=>r.samples[2][2]=Infinity,r=>r.samples.at(-1)[1]=100,r=>r.samples[0][0]=10,r=>r.timeSec=NaN]){const bad=structuredClone(record);mutate(bad);check(normalizeGhostStore({version:1,records:[bad]}).records.length===0,'malformed or incompatible storage rejected');}
const extras=normalizeGhostStore({version:1,records:[{...record,untrustedExtra:'x'.repeat(10000)}]});check(!Object.hasOwn(extras.records[0],'untrustedExtra'),'unknown stored fields are discarded');
const many=Array.from({length:15},(_,i)=>{const row={...long.record,seed:i,lastUsedAt:i,recordedAt:i};row.key=ghostKey(row.playerId,row);return row;});store=normalizeGhostStore({version:1,records:many});check(store.records.length===MAX_GHOSTS,'store caps recording count');check(store.records[0].seed===14&&store.records.at(-1).seed===3,'least recently used runs are pruned first');check(new TextEncoder().encode(JSON.stringify(store)).length<=MAX_GHOST_BYTES,'serialized store remains within byte cap');check(mergeGhostStores({version:1,records:[record]},{version:1,records:[quicker]}).records[0].timeSec===115,'cross-tab merge retains faster record');
const memory=new Map(),storage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)};check(saveGhosts(store,storage)&&loadGhosts(storage).records.length===12,'storage round trip');memory.set(GHOST_KEY,'{bad');check(loadGhosts(storage).records.length===0,'corrupt storage fails safely');const blocked={getItem(){throw Error('denied');},setItem(){throw Error('denied');}};check(loadGhosts(blocked).records.length===0&&!saveGhosts(store,blocked),'storage denial fails safely');check(readGhostEnabled(blocked),'ghost default enabled if settings unavailable');check(saveGhostEnabled(false,storage)&&!readGhostEnabled(storage),'optional setting persists');

// Full App integration uses the real steering, all sequential gates and both laps.
memory.clear();globalThis.localStorage=storage;const app=new App();app.autopilot=true;app.startCampaign({...context,startStage:stageIndex});
for(let i=0;i<3000&&['countdown','racing','ticket'].includes(app.duel.state.status);i++)app.advance(.1);
check(app.duel.state.results?.completed===true,'real physics completes both Time Trial laps');check(app.ghosts.records.length===1&&app.duel.state.results.ghostRecorded,'actual fastest completed run saved');check(app.ghostRecorder===null&&app.ghostPose===null,'result stops recording and playback');check(loadGhosts(storage).records.length===1,'ghost saved separately from wallet');
const saved=app.ghosts.records[0],wallet=app.profile.credits;app.duel.emit({stageResult:app.duel.state.results});check(app.ghosts.records.length===1&&app.profile.credits===wallet,'repeated result cannot duplicate recording or reward');
app.restart();check(app.ghostPose?.s===0&&app.ghostStatus==='playing','restart plays compatible saved ghost at start');app.advance(4);const before=app.ghostPose.s,clockBefore=app.duel.state.stageTimeSec;app.togglePause();app.advance(3);check(app.ghostPose.s===before&&app.duel.state.stageTimeSec===clockBefore,'pause freezes both clocks');app.resume();app.setGhostEnabled(false);check(app.ghostPose===null&&app.ghostStatus==='off','toggle hides ghost immediately');check(!!app.ghostRecorder,'turning off playback still records new best attempts');app.setGhostEnabled(true);check(app.ghostPose!==null,'toggle restores playback');app.returnToMenu();check(app.ghostRecorder===null&&app.ghostPose===null,'abandon clears live ghost state');check(app.ghosts.records[0].timeSec===saved.timeSec,'abandon cannot replace saved best');
const first=app.player.id;app.addPlayer('New driver');check(!app.getGhostRecord({...context,startStage:stageIndex}),'another named player has no inherited ghost');app.selectPlayer(first);check(!!app.getGhostRecord({...context,startStage:stageIndex}),'switching back restores own setup record');
// Existing faster profile records remain authoritative even if their ghost was pruned.
app.profile.personalBests[bestKey({...context,seed:app.seed})]=1;app._saveProfile();app.ghosts=createGhostStore();memory.delete(GHOST_KEY);app.startCampaign({...context,startStage:stageIndex});for(let i=0;i<3000&&['countdown','racing','ticket'].includes(app.duel.state.status);i++)app.advance(.1);check(app.duel.state.results.completed&&app.ghosts.records.length===0,'slower finish cannot create a misleading personal-best ghost');
app.returnToMenu();globalThis.localStorage=blocked;const offline=new App();offline.autopilot=true;offline.startCampaign({...context,startStage:stageIndex});for(let i=0;i<3000&&['countdown','racing','ticket'].includes(offline.duel.state.status);i++)offline.advance(.1);check(offline.ghosts.records.length===1&&offline.ghostSaved===false,'blocked storage preserves a session-only best ghost');offline.restart();check(offline.ghostPose!==null,'session-only ghost can be raced after restart');
console.log(`Time Trial ghosts: ${count} assertions passed`);
