import './style.css';
import { App } from './app.js';
import { LIGHTING_MOODS } from './lighting-moods.js';
import { CARS, DIFFICULTY, COURSE, DRIVE, CPU_DIFFICULTY } from './config.js';
import { createProfile, getUpgradeLevels, isCarUnlocked, upgradedCar, UPGRADE_COSTS, UPGRADE_TYPES, CAR_PRICES, CPU_REWARDS, bestKey, eventKey, milestoneProgress } from './progression.js';
import {getLeaderboard} from './leaderboard.js';
import {RouteMap} from './route-map.js';
import {CoursePreview} from './course-preview.js';
import {PAINT_PRESETS,getPaintState} from './paint-presets.js';
import {ROUTE_VARIANTS,getRouteVariantForSeed,supportsRouteVariants} from './route-variants.js';

const app = new App();
const root = document.querySelector('#app');
const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15M13 5l7 7-7 7"/></svg>';
const sound = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5ZM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/></svg>';
const choices = { car: app.duel.state.car, difficulty: app.duel.state.difficulty, cpuDifficulty:app.cpuDifficulty, mode: 'duel', startStage: app.menuStage || 0 };
let rendererPromise,rendererHandle,uiDisposed=false,lastScreen, garageOpen = false, garageCar = choices.car, garageMessage = '', playersOpen=false,playerMessage='',leaderboardOpen=false;
let lastEventResult=null;
const domEvents=new AbortController();
const boardFilter={stage:choices.startStage,car:''};
const profile = () => app.profile || createProfile();
const credits = value => Math.floor(value || 0).toLocaleString();
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

root.innerHTML = `<div id="stage" class="in-menu"><div id="view3d" aria-label="Three-dimensional driving scene"></div><div class="film-grain"></div><div id="overlay">
  <header class="masthead"><a class="wordmark" href="#" data-action="menu" aria-label="The Duel main menu"><span class="brand-slashes">///</span> THE DUEL <span class="edition">REDLINE</span></a><div class="utility-controls"><span id="menu-location" class="location-label"><i></i> MOJAVE COUNTY, USA</span><button id="garage-open" class="garage-wallet" data-action="garage"><span>GARAGE</span><b id="menu-credits">0 CR</b></button><button id="sound-toggle" class="icon-button" data-action="sound" aria-label="Mute sound" title="Sound · M">${sound}<span id="sound-caption">SOUND ON</span></button><button id="camera-toggle" class="icon-button race-only" data-action="camera" aria-label="Change camera" title="Camera · C" hidden><svg viewBox="0 0 24 24" fill="none"><path d="m8 6 2-3h4l2 3h5v14H3V6h5Z"/><circle cx="12" cy="12" r="4"/></svg></button><button id="pause-button" class="icon-button race-only" data-action="pause" aria-label="Pause race" title="Pause · Esc" hidden><svg viewBox="0 0 24 24" fill="none"><path d="M8 5v14M16 5v14"/></svg></button></div></header>
  <main id="menu-screen" class="menu-screen">
    <div class="menu-intro"><p class="eyebrow"><i></i> YOUR GARAGE. YOUR NAME. YOUR RACE.</p><h1>THE<span>DUEL</span><em>REDLINE</em></h1><p class="menu-description">Two laps. New horizons.<br>Build your way to the arena.</p></div>
    <section class="race-setup" aria-label="Race setup"><div class="player-controls"><label class="field-label" for="player-select">PLAYER</label><select id="player-select" aria-label="Choose local player"></select><button data-action="new-player" class="small-action">+ NEW</button><button data-action="leaderboard" class="small-action">SCORES ↗</button></div><div class="setup-line scene-line"><label class="field-label" for="scene-select">CIRCUIT</label><select id="scene-select" aria-label="Choose a scene">${COURSE.map((scene,index)=>`<option value="${index}">${scene.name}</option>`).join('')}</select></div><div id="route-choice" class="setup-line route-choice"><span id="route-choice-label" class="field-label">ROUTE</span><div class="segmented" role="group" aria-label="Course route">${ROUTE_VARIANTS.map(route=>`<button class="choice" data-route-variant="${route.id}" aria-pressed="false">${route.label.toUpperCase()}</button>`).join('')}</div></div><div class="setup-line"><span class="field-label">THE CHALLENGE</span><div class="segmented" role="group" aria-label="Race mode"><button class="choice on" data-mode="duel" aria-pressed="true">RIVAL DUEL</button><button class="choice" data-mode="timetrial" aria-pressed="false">TIME TRIAL</button></div></div><div class="setup-line"><span id="cpu-target-label" class="field-label">CPU RIVAL</span><div class="segmented" role="group" aria-label="CPU difficulty">${Object.entries(CPU_DIFFICULTY).map(([key,item])=>`<button class="choice ${choices.cpuDifficulty===key?'on':''}" data-cpu-difficulty="${key}" aria-pressed="${choices.cpuDifficulty===key}">${item.name.toUpperCase()}</button>`).join('')}</div></div><div class="setup-line"><span class="field-label">TRANSMISSION</span><div class="segmented" role="group" aria-label="Difficulty">${Object.entries(DIFFICULTY).map(([key,d]) => `<button class="choice ${choices.difficulty === key ? 'on' : ''}" data-difficulty="${key}" aria-pressed="${choices.difficulty === key}">${d.autoShift ? 'ARCADE / AUTO' : 'PRO / MANUAL'}</button>`).join('')}</div></div><p class="entry-reward" id="entry-reward"></p><p id="event-brief" class="event-brief" hidden></p><label id="ghost-control" class="ghost-control" hidden><input id="ghost-toggle" type="checkbox"><span>BEST GHOST <b id="ghost-record-label"></b></span></label><p id="ghost-hint" class="ghost-hint" hidden>Finish a Time Trial personal best to record your ghost.</p><button id="start-engine" class="start-button" data-action="start"><span>START ENGINE</span>${arrow}</button><p class="start-note">2 LAPS <span>·</span> FIVE EARNABLE CARS <span>·</span> LOCAL PLAYER PROGRESS</p></section>
    <section class="garage" aria-label="Choose your car"><div class="garage-heading"><span class="field-label">CHOOSE YOUR WEAPON</span><label class="graphics-control"><span>GRAPHICS</span><select id="graphics-quality" aria-label="Graphics quality"><option value="high">High</option><option value="performance">Performance</option></select></label><span id="garage-count">01 / ${String(Object.keys(CARS).length).padStart(2,'0')}</span></div><label class="car-picker"><span class="visually-hidden">Choose your car</span><select id="car-select" aria-label="Choose your car">${Object.entries(CARS).map(([key,c])=>`<option value="${key}">${c.name}</option>`).join('')}</select><span class="car-picker-arrow" aria-hidden="true">⌄</span></label><div class="car-specs"><div><b id="car-speed"></b><span>TOP SPEED / MPH</span></div><div><b id="car-gears"></b><span>GEARS</span></div><div><b id="car-character"></b><span>DRIVING CHARACTER</span></div></div><label class="lighting-control"><span>LIGHTING</span><select id="lighting-mood" aria-label="Outdoor lighting">${Object.entries(LIGHTING_MOODS).map(([id,mood])=>`<option value="${id}">${mood.label}</option>`).join('')}<option value="night" disabled hidden>Night event</option></select></label><div class="course-preview" aria-label="Selected course preview"><canvas id="menu-course-map" width="320" height="200" role="img" aria-label="Selected course outline"></canvas><div class="course-preview-details"><div class="course-preview-top"><span id="menu-route-label">ROUTE A</span><span id="scene-length"></span></div><b id="scene-name">${COURSE[0].name}</b><div id="menu-biome-legend" class="menu-biome-legend"></div><div class="course-preview-bottom"><span id="menu-shortcuts"></span><span id="menu-elevation" class="menu-elevation"><canvas id="menu-elevation-profile" width="180" height="28" aria-hidden="true"></canvas><span id="menu-relief"></span></span></div></div></div><button class="garage-tune" data-action="garage">TUNE YOUR CAR <span>→</span></button></section>
    <footer class="menu-footer"><span class="footer-label">BUILT FOR THE DRIVE</span><div class="controls-strip"><span><kbd>W A S D</kbd> DRIVE</span><span><kbd>SPACE</kbd> BOOST</span><span><kbd>C</kbd> CAMERA</span><span><kbd>Q / E</kbd> MANUAL SHIFT</span><span><kbd>ESC</kbd> PAUSE</span></div><a class="build-label audio-credits" href="/assets/audio/credits.html" target="_blank" rel="noopener">ASSET CREDITS ↗</a></footer>
  </main>
  <section id="race-hud" class="hud" aria-label="Race information" hidden><div class="race-progress"><i id="progress-fill"></i></div><div class="race-heading"><p class="eyebrow" id="stage-label"></p><h2 id="stage-name"></h2><p id="stage-objective"></p></div><div class="race-clock"><span class="field-label">RACE TIME</span><b id="race-time">00:00.00</b><span id="penalty-time"></span><div class="lap-readout"><b id="lap-number">LAP 1 / 2</b><span id="lap-time">00:00.00</span></div></div><div class="race-position"><span class="position-number"><b id="race-position">01</b><span id="position-total">/02</span></span><div><span class="field-label" id="gap-label">RIVAL BEHIND</span><b id="rival-gap">0.0 SEC</b></div></div>
  <div class="route-hud"><div class="route-hud-top"><span class="field-label">CIRCUIT / LIVE</span><b id="route-percent">0%</b></div><div class="route-section"><span id="route-section"></span><b id="route-lap">1 / 2</b></div><canvas id="route-map" width="400" height="280" role="img" aria-label="Circuit map with your heading, race actors and shortcut branches"></canvas><div class="route-legend"><span><i class="player-dot"></i> YOU</span><span id="rival-legend"><i class="rival-dot"></i> RIVAL</span><span id="police-legend" hidden><i class="police-dot"></i> PATROL</span></div><div class="route-map-footer"><span id="arena-crush" class="arena-crush" role="status" hidden>CRUSHED 0 / 6</span><span id="shortcut-legend" class="shortcut-legend" hidden>SHORTCUTS <i class="shortcut-a"></i>A <span id="shortcut-b-legend"><i class="shortcut-b"></i>B</span></span><b id="route-remaining"></b></div></div><div class="race-health"><span class="field-label">CHASSIS INTEGRITY</span><span id="lives-display"></span><b id="damage-label">0 / 5 MAJOR CRASHES</b><span id="radar-label">RADAR CLEAR</span><div id="radar-meter" class="radar-meter"><i id="radar-fill"></i></div></div>
  <div class="speedometer"><div class="speed-top"><div class="gear"><span class="field-label">GEAR</span><b id="gear-value">1</b></div><div class="speed"><b id="speed-value">000</b><span>MPH</span></div></div><div class="rpm-track"><i id="rpm-fill"></i></div><div class="rpm-labels"><span>0</span><span>RPM × 1000</span><span id="rpm-value">8</span></div><div class="boost-readout"><span class="field-label">NITRO</span><div class="boost-track"><i id="boost-fill"></i></div><kbd>SPACE</kbd></div><div class="speed-footer"><span id="camera-label">CHASE CAM</span><span><kbd>ESC</kbd> PAUSE</span></div></div><div id="style-score-panel" class="style-score"><b id="style-score">0000</b><span class="field-label">STYLE POINTS</span><span id="combo-label"></span></div><section id="drift-panel" class="drift-panel" aria-label="Drift trial score" hidden><div class="drift-score-row"><div><span>BANKED <small id="drift-target-label"></small></span><b id="drift-banked">0</b></div><div><span>LIVE CHAIN</span><b id="drift-chain">+0 <small id="drift-multiplier">×1.00</small></b></div></div><div class="drift-target-track"><i id="drift-target-fill"></i></div><p id="drift-notice" aria-live="polite">Straighten to bank your chain.</p></section>
  <section id="checkpoint-panel" class="drift-panel checkpoint-panel" aria-label="Checkpoint rush progress" hidden><div class="drift-score-row"><div><span>GATES PASSED</span><b id="checkpoint-passed">0 / 12</b></div><div><span>TIME LEFT</span><b id="checkpoint-time">00:00.00</b></div></div><div class="drift-target-track"><i id="checkpoint-target-fill"></i></div><p id="checkpoint-next">NEXT GATE 1 / 12</p><p id="checkpoint-notice" aria-live="polite">Each gate adds time.</p></section>
  <div id="countdown" class="countdown" hidden><span id="countdown-word">GET READY</span><b id="countdown-number">3</b><p>HOLD W OR ↑ TO ACCELERATE</p></div><div id="race-callout" class="race-callout" aria-live="polite" hidden><span id="callout-kicker"></span><b id="callout-text"></b></div><div id="crash-flash" class="crash-flash" hidden></div></section>
  <div id="modal-layer" class="modal-layer" hidden></div><div id="renderer-error" class="renderer-error" role="alert" hidden><strong>The road couldn't load.</strong><span>Enable browser graphics acceleration, then try again.</span><button class="text-button" data-action="retry-renderer">RETRY GRAPHICS ↗</button></div><div id="renderer-loading" class="renderer-loading"><span></span> FINDING THE OPEN ROAD</div><button id="test-driver" class="test-driver" data-action="manual" hidden>TEST DRIVER ACTIVE · TAKE CONTROL</button>
</div></div>`;

const ui = Object.fromEntries([...root.querySelectorAll('[id]')].map(el => [el.id, el]));
const routeMap=new RouteMap(ui['route-map']);
const coursePreview=new CoursePreview(ui['menu-course-map'],ui['menu-elevation-profile']);
if(import.meta.hot)import.meta.hot.dispose(()=>{uiDisposed=true;domEvents.abort();app.dispose();rendererHandle?.dispose();rendererHandle=null;routeMap.dispose();coursePreview.dispose();});
const text = (id,v) => { if (ui[id].textContent !== String(v)) ui[id].textContent = v; };
const clamp = v => Math.max(0,Math.min(1,Number(v)||0));
const time = seconds => { const t = Math.floor(Math.max(0, Number(seconds)||0)*100); return `${String(Math.floor(t/6000)).padStart(2,'0')}:${String(Math.floor(t/100)%60).padStart(2,'0')}.${String(t%100).padStart(2,'0')}`; };

function ensureRenderer() {
  if (!rendererPromise) {
    ui['renderer-loading'].hidden = false; ui['renderer-error'].hidden = true;
    rendererPromise = import('./render3d.js').then(({attachRenderer}) => { if(uiDisposed)return;rendererHandle=attachRenderer(ui.view3d,app); ui.view3d.classList.add('live'); ui['start-engine'].disabled = false; }).catch(error => {
      if(uiDisposed)return;
      rendererPromise = null; ui['renderer-error'].hidden = false; ui['start-engine'].disabled = true;
      if (['racing','countdown'].includes(app.duel.state.status) && !app.duel.state.paused) app.togglePause();
      console.error('Unable to initialize 3D graphics.',error);
    }).finally(() => { if(!uiDisposed)ui['renderer-loading'].hidden = true; });
  }
  return rendererPromise;
}
function updateMenuCar() {
  if (!isCarUnlocked(profile(), choices.car)) choices.car = 'falcone_f42';
  const car = upgradedCar(CARS[choices.car], getUpgradeLevels(profile(), choices.car));
  app.duel.state.car = choices.car; app.menuCar = choices.car;
  text('car-speed', Math.round(car.topSpeed)); text('car-gears', String(car.gears.length).padStart(2,'0'));
  text('car-character', car.grip >= .9 ? 'PLANTED' : 'UNTAMED');
  text('garage-count', `${String(Object.keys(CARS).indexOf(choices.car)+1).padStart(2,'0')} / ${String(Object.keys(CARS).length).padStart(2,'0')}`);
  text('menu-credits', `${credits(profile().credits)} CR`);
  for(const option of ui['car-select'].options){const key=option.value;option.textContent=isCarUnlocked(profile(),key)?CARS[key].name:`${CARS[key].name} · LOCKED · ${credits(CAR_PRICES[key])} CR`;}
  ui['car-select'].value=choices.car;
  updateEntryReward();
}
function updateEntryReward(){
  const base=CPU_REWARDS[choices.cpuDifficulty],best=profile().personalBests[bestKey({stageIndex:choices.startStage,seed:app.getMenuSeed(choices.startStage),laps:COURSE[choices.startStage]?.laps||2,...choices})];
  const scoreBest=COURSE[choices.startStage].kind==='drift'?getLeaderboard(app.leaderboard,{event:eventKey({stageIndex:choices.startStage,seed:app.getMenuSeed(),laps:2}),car:choices.car,playerId:app.player.id})[0]?.driftScore:null;
  text('entry-reward',`WIN ${credits(base)} CR · LOSS −${credits(base/2)} CR${best?` · CAR BEST ${time(best)}`:''}${scoreBest!=null?` · SCORE BEST ${credits(scoreBest)}`:''}`);
  const stage=COURSE[choices.startStage],stunt=stage?.stuntTrial,drift=stage?.driftTrial,rush=stage?.checkpointRush;text('cpu-target-label',stage.kind==='chase'?'PURSUIT LEVEL':rush?'GATE TIMER':drift?'DRIFT TARGET':stage.stuntTrial||choices.mode==='timetrial'?'TIME TARGET':'CPU RIVAL');ui['event-brief'].hidden=!stunt&&!drift&&!rush;text('event-brief',rush?`Pass all ${rush.gatesPerLap*(stage.laps||2)} gates in order over 2 laps. Start with ${rush.initialTimeSec[choices.cpuDifficulty]} seconds; each gate adds ${rush.extensionSec[choices.cpuDifficulty]}. Missing a gate cannot set a record.`:drift?`Bank ${credits(drift.targets[choices.cpuDifficulty])} drift points in 2 laps / ${drift.timeLimitSec[choices.cpuDifficulty]} seconds. Slide above 45 MPH. Straighten to bank; impacts and dirt lose your live chain.`:stunt?`Land ${stunt.jumps} jumps, crush ${stunt.crushes} cars, and finish both laps within ${stunt.timeLimitSec[choices.cpuDifficulty]} seconds.`:'');
  const record=app.getGhostRecord(choices);ui['ghost-control'].hidden=!record;ui['ghost-hint'].hidden=choices.mode!=='timetrial'||!!record;ui['ghost-toggle'].checked=app.ghostEnabled;
  if(record){const build=Object.values(record.upgrades).reduce((sum,n)=>sum+n,0);text('ghost-record-label',`${time(record.timeSec)} · RECORD BUILD ${build}/21`);ui['ghost-control'].title=Object.entries(record.upgrades).map(([key,level])=>`${UPGRADE_TYPES[key]?.name||key}: ${level}`).join(' · ');}
}
function updatePlayers(){
  ui['player-select'].innerHTML=app.players.players.map(player=>`<option value="${escapeHTML(player.id)}">${escapeHTML(player.name)}</option>`).join('');ui['player-select'].value=app.player.id;
}
function updateMenuScene() {
  if(COURSE[choices.startStage]?.requiredCar&&!isCarUnlocked(profile(),COURSE[choices.startStage].requiredCar))choices.startStage=0;
  const stage = COURSE[choices.startStage] || COURSE[0];
  if(stage.requiredCar)choices.car=stage.requiredCar;
  if(['chase','drift','checkpoint'].includes(stage.kind)||stage.stuntTrial)choices.mode='duel';
  for(const button of root.querySelectorAll('[data-mode]')){button.disabled=(['chase','drift','checkpoint'].includes(stage.kind)||!!stage.stuntTrial)&&button.dataset.mode==='timetrial';button.classList.toggle('on',button.dataset.mode===choices.mode);button.setAttribute('aria-pressed',String(button.dataset.mode===choices.mode));if(button.dataset.mode==='duel')button.textContent=stage.checkpointRush?'CHECKPOINT RUSH':stage.driftTrial?'DRIFT TRIAL':stage.stuntTrial?'STUNT TRIAL':stage.kind==='chase'?'ESCAPE THE PURSUIT':'RIVAL DUEL';}
  const fixedNight=stage.timeOfDay==='night'||stage.theme==='city';ui['lighting-mood'].disabled=fixedNight;ui['lighting-mood'].value=fixedNight?'night':app.lightingMood;
  app.menuStage = choices.startStage; ui['scene-select'].value = choices.startStage;ui['route-choice'].hidden=!supportsRouteVariants(stage);text('route-choice-label',app.getMenuRouteLabel()==='Custom route'?'CUSTOM ROUTE':'ROUTE');
  for(const button of root.querySelectorAll('[data-route-variant]')){const selected=getRouteVariantForSeed(app.getMenuSeed())?.id===button.dataset.routeVariant;button.classList.toggle('on',selected);button.setAttribute('aria-pressed',String(selected));}
  for(const option of ui['scene-select'].options){const item=COURSE[Number(option.value)],locked=item.requiredCar&&!isCarUnlocked(profile(),item.requiredCar);option.disabled=!!locked;option.textContent=`${item.name}${locked?` · UNLOCK ${CARS[item.requiredCar].name.toUpperCase()}`:''}`;}
  const preview=coursePreview.update(app.getMenuCourse(),app.getMenuRouteLabel());
  text('scene-name',stage.name);text('scene-length',`${preview.distanceKm.toFixed(1)} KM · ${preview.laps} LAPS`);text('menu-route-label',app.getMenuRouteLabel().toUpperCase());
  ui['menu-biome-legend'].innerHTML=preview.biomes.map(biome=>`<span><i style="--biome-color:${biome.color}" aria-hidden="true"></i>${escapeHTML(biome.label)}</span>`).join('');
  text('menu-shortcuts',preview.map.gates.length?`${preview.map.gates.length} GATES PER LAP`:preview.map.branches.length?`${preview.map.branches.length} DASHED SHORTCUT${preview.map.branches.length===1?'':'S'}`:'CLOSED CIRCUIT');ui['menu-elevation'].hidden=!preview.showElevation;text('menu-relief',`${preview.reliefMeters} M HEIGHT RANGE`);
  text('menu-location', {desert:'MOJAVE COUNTY, USA',alpine:'THE HIGH ALPINE PASS',coast:'PACIFIC COAST, USA',city:'HARBOR DISTRICT · AFTER DARK'}[stage.theme] || stage.name.toUpperCase());
  updateMenuCar();
}
ui['ghost-toggle'].addEventListener('change',event=>app.setGhostEnabled(event.target.checked));
ui['lighting-mood'].addEventListener('change',event=>{app.setLightingMood(event.target.value);ui['lighting-mood'].value=app.lightingMood;});
ui['graphics-quality'].value=app.ambientOcclusionEnabled?'high':'performance';
ui['graphics-quality'].addEventListener('change',event=>app.setGraphicsQuality(event.target.value));
ui['car-select'].addEventListener('change',event=>{const car=event.target.value;if(!isCarUnlocked(profile(),car)){ui['car-select'].value=choices.car;openGarage(car);return;}choices.car=car;if(COURSE[choices.startStage]?.requiredCar&&COURSE[choices.startStage].requiredCar!==car)choices.startStage=0;updateMenuScene();});
ui['scene-select'].addEventListener('change', e => { choices.startStage = Math.max(0, Math.min(COURSE.length-1, Number(e.target.value) || 0)); updateMenuScene(); });
ui['player-select'].addEventListener('change',e=>{app.selectPlayer(e.target.value);updatePlayers();updateMenuScene();lastScreen=null;renderState(app.duel.state);});
function openGarage(car = choices.car) {
  if (app.duel.state.status !== 'menu') return;
  garageCar = car; garageMessage = ''; garageOpen = true; playersOpen=leaderboardOpen=false; app.menuCar = car; lastScreen = null; renderState(app.duel.state);
}
function closeGarage() { garageOpen = false; lastScreen = null; updateMenuCar(); renderState(app.duel.state); ui['garage-open'].focus({preventScroll:true}); }
function refreshGarage(message) {
  garageMessage = message || ''; lastScreen = null; updateMenuCar(); app.menuCar = garageCar; renderState(app.duel.state);
}
root.addEventListener('click',e => {
  const button = e.target.closest('button,[data-action]'); if (!button) return;
  if(button.dataset.routeVariant){if(app.setRouteVariant(button.dataset.routeVariant))updateMenuScene();return;}
  if(button.dataset.challenge!=null){choices.startStage=Number(button.dataset.challenge);choices.car=COURSE[choices.startStage].requiredCar;updateMenuScene();closeGarage();return;}
  if (button.dataset.garageCar) { garageCar = button.dataset.garageCar; app.menuCar = garageCar; garageMessage = ''; lastScreen = null; renderState(app.duel.state); return; }
  if(button.dataset.paint){const result=app.purchasePaint(garageCar,button.dataset.paint);refreshGarage(result.ok?`${PAINT_PRESETS[button.dataset.paint].name} applied to ${CARS[garageCar].name}.${result.purchased?` Purchased for ${credits(result.cost)} credits.`:''}`:result.reason);return;}
  if (button.dataset.upgrade) { const result = app.purchaseUpgrade(garageCar, button.dataset.upgrade); refreshGarage(result.ok ? `${UPGRADE_TYPES[button.dataset.upgrade].name} upgraded to level ${getUpgradeLevels(profile(), garageCar)[button.dataset.upgrade]}.` : result.reason); return; }
  if (button.dataset.car && !isCarUnlocked(profile(), button.dataset.car)) { openGarage(button.dataset.car); return; }
  for (const key of ['car','difficulty','mode','cpuDifficulty']) if (button.dataset[key]) { choices[key] = button.dataset[key]; for (const sibling of button.parentElement.children) { sibling.classList.toggle('on', sibling === button); sibling.setAttribute('aria-pressed', String(sibling === button)); } if (key === 'car') {if(COURSE[choices.startStage]?.requiredCar&&COURSE[choices.startStage].requiredCar!==choices.car)choices.startStage=0;updateMenuScene();}updateEntryReward();return; }
  if(button.closest('form')&&button.type==='submit')return;
  e.preventDefault();
  switch (button.dataset.action) {
    case 'start': garageOpen = playersOpen = leaderboardOpen = false; app.startCampaign(choices); break;
    case 'new-player':playersOpen=true;leaderboardOpen=garageOpen=false;playerMessage='';lastScreen=null;renderState(app.duel.state);root.querySelector('#new-player-name')?.focus();return;
    case 'player-close':playersOpen=false;lastScreen=null;break;
    case 'leaderboard':leaderboardOpen=true;playersOpen=garageOpen=false;boardFilter.stage=choices.startStage;lastScreen=null;break;
    case 'leaderboard-close':leaderboardOpen=false;lastScreen=null;break;
    case 'garage': openGarage(); return;
    case 'garage-close': closeGarage(); return;
    case 'unlock-car': { const result = app.unlockCar(garageCar); if(result.ok) {choices.car = garageCar;updateMenuScene();}refreshGarage(result.ok ? `${CARS[garageCar].name} is yours.${COURSE.some(event=>event.requiredCar===garageCar)?' A new challenge is now unlocked.':' Ready for the next race.'}` : result.reason); return; }
    case 'arena':choices.startStage=COURSE.findIndex(scene=>scene.arena);choices.car='titan_monster';updateMenuScene();closeGarage();return;
    case 'garage-select': choices.car = garageCar;if(COURSE[choices.startStage]?.requiredCar&&COURSE[choices.startStage].requiredCar!==garageCar)choices.startStage=0;updateMenuScene();closeGarage(); return;
    case 'sound': app.audio.unlock(); app.audio.toggleMute(); break;
    case 'camera': app.cycleCamera(); break;
    case 'pause': app.togglePause(); break;
    case 'resume': app.resume(); break;
    case 'restart': app.requestNavigation('restart'); break;
    case 'menu': garageOpen = playersOpen = leaderboardOpen = false; app.requestNavigation('menu');if(app.duel.state.status==='menu'){updateMenuCar();updateMenuScene();}break;
    case 'confirm-leave':app.confirmNavigation();if(app.duel.state.status==='menu'){updateMenuCar();updateMenuScene();}break;
    case 'keep-racing':app.cancelNavigation();break;
    case 'next': app.duel.nextStage(); break;
    case 'ticket': app.duel.ackTicket(); break;
    case 'retry-renderer': ensureRenderer(); break;
    case 'manual': app.autopilot = false; break;
    default: return;
  }
  renderState(app.duel.state);
},{signal:domEvents.signal});
const metric = (label,value,accent=false) => `<div class="result-metric${accent?' accent':''}"><span class="field-label">${label}</span><b>${value}</b></div>`;
const action = (label,verb,primary=false) => `<button class="${primary?'start-button':'secondary-button'}" data-action="${verb}"><span>${label}</span>${primary?arrow:''}</button>`;
function playerScreen(){
  const history=profile().history.slice(-5).reverse();
  return `<section class="career-panel player-panel" role="dialog" aria-modal="true" aria-labelledby="player-title"><header class="shop-heading"><div><p class="eyebrow">LOCAL PLAYERS</p><h2 id="player-title">A NAME ON THE GRID.</h2></div><button class="shop-close" data-action="player-close" aria-label="Close player setup">×</button></header><p>Each player has their own credits, cars, upgrades and race history. Everyone on this computer shares the leaderboard.</p><form id="new-player-form"><label for="new-player-name">NEW PLAYER NAME</label><div><input id="new-player-name" name="playerName" maxlength="24" autocomplete="off" placeholder="Your racing name" required><button class="secondary-button" type="submit">CREATE PLAYER</button></div><p role="status" class="career-message">${escapeHTML(playerMessage)}</p></form><h3>${escapeHTML(app.player.name)} · RECENT RACES</h3><div class="player-history">${history.length?history.map(row=>`<div><span>${escapeHTML(COURSE.find(scene=>scene.id===row.eventId)?.name||'Race')}<small>${escapeHTML(CARS[row.car]?.name||'Car')} · ${row.won?'WIN':row.completed?'LOSS':'DNF'}</small></span><b>${row.reward<0?'−':'+'}${credits(Math.abs(row.reward))} CR</b></div>`).join(''):'<p>Complete your first race to start your history.</p>'}</div></section>`;
}
function leaderboardScreen(){
  const stage=COURSE[boardFilter.stage]||COURSE[0],drift=stage.kind==='drift',rush=stage.kind==='checkpoint',event=eventKey({stageIndex:boardFilter.stage,seed:app.getMenuSeed(boardFilter.stage),laps:stage.laps||2});
  const rows=getLeaderboard(app.leaderboard,{event,car:boardFilter.car});
  const description=rush?"Fastest successful checkpoint runs. All gates and both laps must be completed before the earned deadline. Time includes penalties.":drift?"Each player's highest banked score for this car from a successful trial. Equal scores are ranked by finish time, including penalties.":"Each player's fastest valid finish for this circuit, route and car. Both laps count, including time penalties.";
  const resultRows=rows.map((row,index)=>{const challenge=rush?'CHECKPOINT RUSH':drift?'DRIFT TRIAL':stage.stuntTrial?'STUNT TRIAL':stage.kind==='chase'?'PURSUIT':row.mode==='timetrial'?'TIME TRIAL':'DUEL',difficultyLabel=stage.kind==='chase'?'PURSUIT':rush||drift||stage.stuntTrial||row.mode==='timetrial'?'TARGET':'CPU';
    return `<tr class="${row.playerId===app.player.id?'current-player':''}"><td>${String(index+1).padStart(2,'0')}</td><td><b>${escapeHTML(row.playerName)}</b><small>${escapeHTML(CARS[row.car]?.name||row.car)}</small></td><td><b>${drift?`${credits(row.driftScore)} PTS`:time(row.timeSec)}</b><small>${drift?`${time(row.timeSec)} · TARGET ${credits(row.driftTarget)}`:rush?`${row.checkpointsPassed} / ${row.checkpointsRequired} GATES`:`${row.laps} LAPS`}</small></td><td><b>${escapeHTML(row.cpuDifficulty.toUpperCase())} ${difficultyLabel} · ${row.difficulty==='pro'?'MANUAL':'AUTO'}</b><small title="${escapeHTML(Object.entries(row.upgrades).map(([key,level])=>`${UPGRADE_TYPES[key].name} ${level}`).join(', '))}">${Object.values(row.upgrades).reduce((n,level)=>n+level,0)} / 21 UPGRADES · ${challenge}</small></td></tr>`;
  }).join('');
  return `<section class="career-panel leaderboard-panel" role="dialog" aria-modal="true" aria-labelledby="leaderboard-title"><header class="shop-heading"><div><p class="eyebrow">THIS COMPUTER · LOCAL LEADERBOARD</p><h2 id="leaderboard-title">${drift?'SCORES TO CHASE.':'NAMES TO CHASE.'}</h2></div><button class="shop-close" data-action="leaderboard-close" aria-label="Close leaderboard">×</button></header><p>${description}</p><div class="leaderboard-filters"><label>CIRCUIT<select data-board-filter="stage" aria-label="Leaderboard circuit">${COURSE.map((scene,index)=>`<option value="${index}" ${index===boardFilter.stage?'selected':''}>${scene.name}</option>`).join('')}</select></label><label>CAR<select data-board-filter="car" aria-label="Leaderboard car"><option value="">All cars</option>${Object.entries(CARS).map(([key,item])=>`<option value="${key}" ${key===boardFilter.car?'selected':''}>${item.name}</option>`).join('')}</select></label></div><div class="leaderboard-table"><table><thead><tr><th>RANK</th><th>PLAYER / CAR</th><th>${drift?'SCORE / TIME':'TIME'}</th><th>RACE / BUILD</th></tr></thead><tbody>${resultRows||`<tr><td colspan="4" class="empty-board">${drift?'No scores here yet. Reach the target and finish both laps before the deadline.':'No times here yet. Finish both laps to set the first record.'}</td></tr>`}</tbody></table></div><p class="career-note">Saved in this browser on this computer. ${app.getMenuRouteLabel(boardFilter.stage)} · ${stage.laps||2} laps. ${app.leaderboardSaved===false?'Storage is unavailable; new records last for this session.':''}</p></section>`;
}
root.addEventListener('submit',event=>{
  if(event.target.id!=='new-player-form')return;event.preventDefault();const input=root.querySelector('#new-player-name'),result=app.addPlayer(input.value);
  if(result.ok){playersOpen=false;updatePlayers();updateMenuScene();}else playerMessage=result.reason;
  lastScreen=null;renderState(app.duel.state);if(!result.ok)root.querySelector('#new-player-name')?.focus();
},{signal:domEvents.signal});
root.addEventListener('change',event=>{const key=event.target.dataset.boardFilter;if(!key)return;boardFilter[key]=key==='stage'?Number(event.target.value):event.target.value;lastScreen=null;renderState(app.duel.state);},{signal:domEvents.signal});
function paintPanel(saved,carKey){
  const state=getPaintState(saved,carKey),unlocked=isCarUnlocked(saved,carKey);
  return `<section class="paint-panel" aria-label="Paint finishes"><div class="paint-heading"><h3>PAINT FINISH</h3><span>Appearance only · per car</span></div><div class="paint-options">${Object.values(PAINT_PRESETS).map(preset=>{const owned=state.owned.includes(preset.id),selected=state.selected===preset.id,color=preset.appearance?.color??CARS[carKey].color,disabled=!unlocked||selected||(!owned&&saved.credits<preset.price);return `<button class="paint-choice ${selected?'selected':''} ${preset.id}" data-paint="${preset.id}" ${disabled?'disabled':''} aria-pressed="${selected}" aria-label="${selected?`${preset.name} applied`:owned?`Apply ${preset.name} for free`:`Buy and apply ${preset.name} for ${preset.price} credits`}"><i aria-hidden="true" style="--paint-color:#${color.toString(16).padStart(6,'0')}"></i><span><b>${preset.name}</b><small>${preset.finish}</small></span><strong>${!unlocked?'LOCKED':selected?'APPLIED':owned?'APPLY':`BUY & APPLY · ${credits(preset.price)} CR`}</strong></button>`;}).join('')}</div></section>`;
}
function milestonePanel(saved){
  const rows=milestoneProgress(saved),earned=rows.filter(row=>row.earned).length;
  return `<details class="milestone-panel"><summary><span>DRIVING MILESTONES</span><b>${earned} / ${rows.length} EARNED</b></summary><p>One-time rewards for ${escapeHTML(app.player.name)}. Complete both laps to qualify.</p><ul>${rows.map(row=>`<li class="${row.earned?'earned':''}"><div><b>${row.name}</b><span>${row.description}</span></div><strong aria-label="${row.earned?'Earned':`${row.reward} credits`}">${row.earned?'✓ EARNED':`+${credits(row.reward)} CR`}</strong>${row.total>1?`<progress value="${row.progress}" max="${row.total}" aria-label="Campaign circuits won: ${row.progress} of ${row.total}"></progress><small>${row.progress} / ${row.total} CIRCUITS</small>`:''}</li>`).join('')}</ul></details>`;
}
function garageScreen() {
  const saved = profile(), owned = isCarUnlocked(saved, garageCar), car = CARS[garageCar];
  const levels = getUpgradeLevels(saved, garageCar), tuned = upgradedCar(car, levels);
  const price = CAR_PRICES[garageCar] || 0;
  const maximumAcceleration=Math.max(...Object.values(CARS).map(item=>item.accel*1.12)),maximumBraking=Math.max(...Object.values(CARS).map(item=>item.braking*1.54));
  const capabilities=[['ACCELERATION',tuned.accel/maximumAcceleration],['ROAD GRIP',tuned.grip/1.2],['OFFROAD PACE',(tuned.offRoadSpeed??68)/125,`${Math.round(tuned.offRoadSpeed??68)} MPH`],['BRAKING',tuned.braking/maximumBraking]];
  const capabilityStats=`<div class="car-capabilities" aria-label="Car capabilities">${capabilities.map(([label,value,display])=>`<div><span>${label}</span><b>${display||`${(clamp(value)*10).toFixed(1)}<small> / 10</small>`}</b><i aria-hidden="true"><em style="width:${clamp(value)*100}%"></em></i></div>`).join('')}</div><p class="capability-note">Ratings use the same scale for every car. ${owned?'Your installed upgrades are included.':'Compare this car before unlocking it.'} Offroad pace is its loose-surface target.</p>`;

  const pitch={aurora_gt:['CARBON GT','Precision at speed.','Carbon aero, gold wheels and balanced grip.'],dusthawk_rally:['RALLY BUILT','Take the rough line.','Rally tires and dirt grip. Unlock Ridge Rally and Timberline Checkpoint Rush.'],banshee_muscle:['BIG MUSCLE','Make every straight count.','Muscle for Midnight Chase and the Neon Drift Trial.'],viper_proto:['TRACK PROTOTYPE','Chase the lap record.','Light weight, sharp braking and fast aero.'],titan_monster:['MONSTER CLASS','Unlock the arena.','Giant tires, crushing weight and entry to Titan Monster Arena.']}[garageCar]||['YOUR CAR','Make it yours.','Tune seven systems to suit the way you drive.'];
  const cards = Object.entries(UPGRADE_TYPES).map(([type, upgrade], index) => {
    const level = levels[type], cost = UPGRADE_COSTS[level], full = level === 3;
    return `<article class="upgrade-card"><div class="upgrade-title"><span class="upgrade-number">0${index+1}</span><h3>${upgrade.name}</h3><b>${level} / 3</b></div><p>${upgrade.description}</p><div class="upgrade-levels" aria-label="Level ${level} of 3">${Array.from({length:3},(_,i)=>`<i class="${i<level?'installed':''}"></i>`).join('')}</div><button data-upgrade="${type}" ${full||saved.credits<cost?'disabled':''} aria-label="${full?`${upgrade.name} fully upgraded`:`Upgrade ${upgrade.name} to level ${level+1} for ${cost} credits`}"><span>${full?'FULLY TUNED':`LEVEL ${level+1}`}</span><b>${full?'✓':`${credits(cost)} CR`}</b></button></article>`;
  }).join('');
  return `<section class="garage-panel" role="dialog" aria-modal="true" aria-labelledby="garage-title"><header class="shop-heading"><div><p class="eyebrow"><i></i> THE GARAGE</p><h2 id="garage-title">MAKE IT YOURS.</h2></div><div class="shop-wallet"><span>YOUR CREDITS</span><b>${credits(saved.credits)}<small> CR</small></b></div><button class="shop-close" data-action="garage-close" aria-label="Close garage">×</button></header><nav class="shop-cars" aria-label="Garage cars">${Object.entries(CARS).map(([key,item])=>`<button data-garage-car="${key}" class="${key===garageCar?'on':''}" aria-pressed="${key===garageCar}"><i style="--car-color:#${item.color.toString(16).padStart(6,'0')}"></i><span>${item.name}</span><small>${isCarUnlocked(saved,key)?'OWNED':`${credits(CAR_PRICES[key])} CR`}</small></button>`).join('')}</nav><div class="shop-summary"><div><span class="field-label">${owned?'YOUR BUILD':'UNLOCK THE NEXT LEVEL'}</span><h3>${car.name}</h3></div><div><b>${Math.round(tuned.topSpeed)}</b><span>TOP SPEED / MPH</span></div><div><b>${tuned.gears.length}</b><span>GEARS</span></div></div>${capabilityStats}${paintPanel(saved,garageCar)}${owned?`<div class="upgrade-grid">${cards}</div>`:`<div class="unlock-card"><div><p class="eyebrow">${pitch[0]}</p><h3>${pitch[1]}</h3><p>${pitch[2]}</p></div><div class="unlock-price"><b>${credits(price)}<small> CR</small></b><button class="start-button" data-action="unlock-car" ${saved.credits<price?'disabled':''}><span>UNLOCK CAR</span>${arrow}</button><p>${saved.credits<price?`Earn ${credits(price-saved.credits)} more credits to unlock.`:'Ready for your garage.'}</p></div></div>`}${milestonePanel(saved)}<p class="garage-message" role="status" aria-live="polite">${escapeHTML(garageMessage)||'Win races for credits. Improve a car best for a bonus. Upgrades apply next race.'}</p><footer class="shop-footer"><p>${app.profileSaved===false?'Progress is saved for this session only.':'Progress saves in this browser.'}</p>${owned?COURSE.map((event,index)=>event.requiredCar===garageCar?`<button class="secondary-button challenge-entry" data-challenge="${index}">ENTER ${event.name.toUpperCase()}</button>`:'').join(''):''}${owned?action('DRIVE THIS CAR','garage-select',true):action('BACK TO THE ROAD','garage-close')}</footer></section>`;
}
function modalScreen(s) {
  const r = s.results || {}; let eyebrow='',title='',description='',metrics='',actions='';
  if(app.pendingNavigation){const leaving=app.pendingNavigation.action==='menu';return `<section class="result-panel" role="dialog" aria-modal="true" aria-labelledby="abandon-title"><p class="eyebrow">RACE IN PROGRESS</p><h2 id="abandon-title">${leaving?'LEAVE THIS<br>RACE?':'START<br>OVER?'}</h2><p class="result-description">${leaving?'Leaving':'Restarting'} counts as a loss. ${app.pendingNavigation.charge?`${credits(app.pendingNavigation.charge)} credits will be deducted.`:'Your balance is zero, so no credits will be deducted.'} This race will not enter the leaderboard.</p><div class="result-actions">${action('KEEP RACING','keep-racing',true)}${action(leaving?'LEAVE RACE':'RESTART RACE','confirm-leave')}</div></section>`;}
  if (s.paused) { eyebrow='TAKE A BREATH'; title='ROAD<br>ON HOLD.'; description='The clock is paused. Pick up where you left off.'; metrics=metric('EVENT',COURSE[s.stageIndex].name)+metric('TIME',time(s.stageTimeSec)); actions=action('BACK TO THE ROAD','resume',true)+action('RESTART RUN','restart')+action('MAIN MENU','menu'); }
  else if (s.status==='ticket') { const t=s.police.ticket; eyebrow='HIGHWAY PATROL'; title='BUSTED.'; description=`${t.speedMph} mph in a ${t.limitMph} zone. The patrol caught up.`; metrics=metric('TIME PENALTY',`+${t.penaltySec} SEC`,true)+metric('FINE',`$${t.fine}`); actions=action('GET BACK OUT THERE','ticket',true)+action('MAIN MENU','menu'); }
  else if (s.status==='stage_result') {
    lastEventResult={state:s,stageIndex:s.stageIndex,runId:app.runId,result:r};
    const stage=COURSE[s.stageIndex],drift=stage.kind==='drift',rush=stage.kind==='checkpoint',stunt=r.objective==='stuntTrial',kind=rush?'CHECKPOINT RUSH':drift?'DRIFT TRIAL':stunt?'STUNT TRIAL':stage.kind==='chase'?'PURSUIT':stage.arena?'ARENA':stage.kind==='rally'?'RALLY':'CIRCUIT';
    eyebrow=`${kind} / ${r.won?'VICTORY':r.completed?'COMPLETE':'DNF'}`;title=r.timeout?'TIME RAN<br>OUT.':r.objectiveMissed?(rush?'GATES<br>MISSED.':drift?'TARGET<br>MISSED.':'STUNTS NOT<br>DONE.'):r.won?'OWN THE<br>FINISH.':'SO CLOSE.';
    description=r.won?`${r.personalBest?(r.previousBest==null?'First time recorded for this car. Beat it to earn a best-time bonus. ':'A new best for this car. '):''}${r.winStreak>=3?`${r.winStreak} wins in a row. Streak bonus earned.`:'Both laps are in the books.'}`:r.timeout?'The pursuit deadline passed. The car survives, but this run does not enter the leaderboard.':s.mode==='timetrial'?'You finished both laps but missed the target time. Car-best bonuses still count.':'Your rival took this one. Car-best bonuses still count.';
    if(stunt)description=`${r.timeout?'The stunt deadline passed.':r.objectiveMissed?'Both laps finished, but the stunt targets were missed.':'Both laps and the stunt targets are complete.'} ${r.jumps||0} / ${r.targets?.jumps||s.objective?.targetJumps||4} landed jumps · ${r.crushCount||0} / ${r.targets?.crushes||s.objective?.targetCrushes||4} cars crushed.`;
    if(drift)description=`${r.timeout?'The deadline passed.':r.objectiveMissed?'Both laps finished, but the drift target was missed.':'Both laps and the drift target are complete.'} Banked ${credits(r.driftScore)} / ${credits(r.driftTarget||s.objective?.targetScore)} points. Best chain ${credits(r.driftBestChain)}. Time ${time(r.timeSec??r.stageTimeSec)}.${r.driftScoreImproved?' A new car score best.':''}${r.won?'':' Only successful trials set a car best.'}`;
    if(rush)description=`${r.timeout?'The checkpoint clock ran out.':r.objectiveMissed?'Both laps finished, but some gates were missed.':'Every gate cleared. Both laps complete.'} ${r.checkpointsPassed||0} / ${r.checkpointsRequired||s.checkpointRush?.total||12} gates passed. ${r.checkpointMisses||0} missed. Time ${time(r.timeSec??r.stageTimeSec)}.${r.won?'':' Only successful runs set a car best.'}`;
    if(!r.won)description+=' The loss charge is half the event win reward, down to zero credits.';
    metrics=(rush?metric('GATES PASSED',`${r.checkpointsPassed||0} / ${r.checkpointsRequired||12}`,true)+metric('RACE TIME',time(r.timeSec??r.stageTimeSec)):drift?metric('BANKED POINTS',credits(r.driftScore),true)+metric('TARGET',credits(r.driftTarget||s.objective?.targetScore)):metric('RACE TIME',time(r.timeSec??r.stageTimeSec),true)+metric('CAR BEST',r.best==null?'—':time(r.best)))+metric(r.creditReward<0?'CREDITS LOST':'CREDITS EARNED',`${r.creditReward<0?'−':'+'}${credits(Math.abs(r.creditReward||0))}`,true);
    const atEnd=!!stage.kind||!COURSE[s.stageIndex+1]||!!COURSE[s.stageIndex+1].kind;
    actions=r.timeout?action('TRY AGAIN','restart',true)+action('MAIN MENU','menu'):action(atEnd?'FINISH THE RUN':'NEXT CIRCUIT','next',true)+action('RESTART RUN','restart')+action('MAIN MENU','menu');
  }
  else if (s.status==='gameover') { eyebrow=s.catastrophic?'CATASTROPHIC DAMAGE':'END OF THE ROAD'; title=s.catastrophic?'TOTALLED.':'ONE MORE<br>RUN?'; description=(s.catastrophic?'Five major crashes. The car is destroyed.':'This race is over.')+' The loss costs half the event win reward, down to zero credits.'; metrics=metric('RACE TIME',time(s.stageTimeSec))+metric('CREDITS LOST',`−${credits(Math.abs(r.creditReward||0))}`,true)+metric('BALANCE',`${credits(profile().credits)} CR`); actions=action('RUN IT BACK','restart',true)+action('MAIN MENU','menu'); }
  else if (s.status==='complete') {
    const stage=COURSE[s.stageIndex];
    if(stage?.kind){
      // nextStage replaces the settlement payload with a generic run summary.
      // Retain the result that this UI just showed, tied to the actual run/event.
      const result=lastEventResult?.state===s&&lastEventResult.stageIndex===s.stageIndex&&lastEventResult.runId===app.runId?lastEventResult.result:{};
      const won=result.won===true,known=typeof result.won==='boolean',rush=stage.kind==='checkpoint',drift=stage.kind==='drift',stunt=!!stage.stuntTrial;
      eyebrow=`${escapeHTML(stage.name.toUpperCase())} / ${known&&won?'VICTORY':'COMPLETE'}`;
      title=!won?'RUN<br>COMPLETE.':rush?'GATES<br>CLEARED.':drift?'DRIFT<br>MASTERED.':stunt?'STUNTS<br>COMPLETE.':stage.kind==='chase'?'CITY<br>ESCAPED.':stage.kind==='rally'?'TRAIL<br>CONQUERED.':'ARENA<br>CONQUERED.';
      description=!won?`${escapeHTML(stage.name)} is complete.${known?' The winning target was not met. Try another run.':''}`:rush?'Every checkpoint passed in order. Both laps complete before the clock ran out.':drift?'Drift target reached. Both city laps complete before the deadline.':stunt?'Both laps, the landed jumps and the crush targets are complete.':stage.kind==='chase'?'Both city laps complete. You escaped the pursuit before the deadline.':stage.kind==='rally'?'Both gravel laps complete. You conquered Ridge Rally.':'Both stadium laps complete. The arena is yours.';
      metrics=metric('RACE TIME',time(result.timeSec??s.stageTimeSec+(s.racePenaltySec||0)),true);
      metrics+=rush?metric('GATES PASSED',`${result.checkpointsPassed??s.checkpointRush?.passed??0} / ${result.checkpointsRequired??s.checkpointRush?.total??12}`):drift?metric('BANKED POINTS',credits(result.driftScore??s.drift?.bankedScore??0)):stunt?metric('LANDED JUMPS',result.jumps??s.jumps??0)+metric('CARS CRUSHED',result.crushCount??s.crushCount??0):metric('LAPS COMPLETE',`${s.completedLaps} / ${s.lapsTotal}`);
      if(Number.isFinite(result.creditReward))metrics+=metric(result.creditReward<0?'CREDITS LOST':'CREDITS EARNED',`${result.creditReward<0?'−':'+'}${credits(Math.abs(result.creditReward))}`,true);
      actions=action('RUN IT AGAIN','restart',true)+action('MAIN MENU','menu');
    }else{
      eyebrow='ALL STAGES COMPLETE';title='HORIZON<br>CONQUERED.';description='From desert heat to mountain air. You made it all the way.';
      metrics=metric('TOTAL TIME',time(r.totalTimeSec),true)+metric('LIVES LEFT',r.lives)+metric('STYLE POINTS',Number(s.score||0).toLocaleString());
      actions=action('CHASE IT AGAIN','restart',true)+action('MAIN MENU','menu');
    }
  }
  else return '';
  const bonus=r.creditBreakdown?Object.entries(r.creditBreakdown).filter(([key,value])=>key!=='base'&&key!=='milestones'&&value>0).map(([key,value])=>`${{clean:'CLEAN RACE',personalBest:'CAR BEST',streak:'WIN STREAK',jumps:'ARENA JUMPS',crush:'CRUSH BONUS',drift:'DRIFT BONUS'}[key]} +${credits(value)}`).join(' · '):'';
  return `<section class="result-panel" role="dialog" aria-modal="true" aria-labelledby="result-title"><p class="eyebrow"><i></i>${eyebrow}</p><h2 id="result-title">${title}</h2><p class="result-description">${description}</p><div class="result-metrics">${metrics}</div>${r.creditCharge?`<p class="result-bonuses">LOSS CHARGE −${credits(r.creditCharge)} CR</p>`:''}${bonus?`<p class="result-bonuses">${bonus}</p>`:''}${r.milestoneAwards?.length?`<p class="result-bonuses milestone-earned" role="status">${r.milestoneAwards.map(award=>`${escapeHTML(award.name).toUpperCase()} +${credits(award.reward)} CR`).join(" · ")}</p>`:''}${r.ghostRecorded?`<p class="result-bonuses ghost-saved">BEST GHOST SAVED${app.ghostSaved===false?' · THIS SESSION ONLY':''}</p>`:''}<div class="result-actions">${actions}</div>${s.paused?'<p class="pause-help">WASD / ARROWS TO DRIVE · SPACE TO BOOST · C TO CHANGE CAMERA<br>Restarting or leaving an active race counts as a loss.</p>':''}</section>`;
}
function renderState(s) {
  ui.overlay.dataset.credits = String(profile().credits);ui.overlay.dataset.ghostStatus=app.ghostStatus;ui.overlay.dataset.ghostRecords=String(app.ghosts.records.length);ui.overlay.dataset.routeVariant=getRouteVariantForSeed(s.status==='menu'?app.getMenuSeed():s.seed)?.id||'custom';
  ui.overlay.dataset.playerId=app.player.id;ui.overlay.dataset.playerName=app.player.name;ui.overlay.dataset.cpuDifficulty=s.cpuDifficulty||choices.cpuDifficulty;ui.overlay.dataset.lap=String(s.currentLap||s.lap||1);
  text('menu-credits', `${credits(profile().credits)} CR`);
  ui.overlay.dataset.status=s.status; ui.overlay.dataset.paused=String(!!s.paused); ui.overlay.dataset.audioState=app.audio?.context?.state||'locked'; ui.overlay.dataset.muted=String(!!app.audio?.muted);
  ui.overlay.dataset.audioSamples=app.audio.sampleStatus;ui.overlay.dataset.majorCrashes=String(s.majorCrashes);ui.overlay.dataset.catastrophic=String(s.catastrophic);
  const showImpact = s.status === 'gameover' && s.impactTimer > 0;
  const screen=`${s.status}:${!!s.paused}:${showImpact}:${app.player.id}:${app.pendingNavigation?.action||''}:${garageOpen}:${playersOpen}:${leaderboardOpen}:${garageOpen ? garageCar + ':' + profile().credits : ''}`;
  if (screen!==lastScreen) {
    lastScreen=screen; const menu=s.status==='menu'; ui.stage.classList.toggle('in-menu',menu); ui.stage.classList.toggle('in-race',!menu); ui['menu-screen'].hidden=!menu; ui['race-hud'].hidden=menu; ui['menu-location'].hidden=!menu; root.querySelectorAll('.race-only').forEach(el=>{el.hidden=menu;});
    ui['garage-open'].hidden = !menu;
    const modal=menu&&playersOpen?playerScreen():menu&&leaderboardOpen?leaderboardScreen():menu && garageOpen ? garageScreen() : menu||showImpact?'':modalScreen(s); ui['modal-layer'].innerHTML=modal; ui['modal-layer'].hidden=!modal; ui.stage.classList.toggle('has-modal',!!modal); ui['countdown'].hidden=s.status!=='countdown'||!!s.paused;
    const challengeLabel=app.duel.stageDef?.kind==='chase'?'PURSUIT':s.objective||s.mode==='timetrial'?'TARGET':'CPU',routeLabel=supportsRouteVariants(app.duel.stageDef)?` · ${(getRouteVariantForSeed(s.seed)?.label||'Custom route').toUpperCase()}`:'';text('stage-label',`${app.player.name.toUpperCase()} · ${(s.cpuDifficulty||choices.cpuDifficulty).toUpperCase()} ${challengeLabel}${routeLabel}`); text('stage-name',app.duel.stageDef?.name||'The open road'); text('stage-objective',s.rival?'BEAT YOUR RIVAL OVER TWO LAPS':'CHASE YOUR CAR PERSONAL BEST');
    ui['pause-button'].setAttribute('aria-label',s.paused?'Resume race':'Pause race');
    if(modal) ui['modal-layer'].querySelector('button')?.focus({preventScroll:true});
  }
  const muted=!!app.audio?.muted; ui['sound-toggle'].classList.toggle('muted',muted); ui['sound-toggle'].setAttribute('aria-label',muted?'Enable sound':'Mute sound'); text('sound-caption',muted?'SOUND OFF':'SOUND ON'); ui['test-driver'].hidden=!app.autopilot;
  if(s.status!=='menu') updateHud(s);
}
function updateHud(s) {
  text('race-time',time(s.stageTimeSec)); text('penalty-time',s.racePenaltySec?`+${Math.round(s.racePenaltySec)} SEC PENALTIES`:'');text('lap-number',`LAP ${s.currentLap||s.lap||1} / ${app.duel.stageDef.laps||2}`);text('lap-time',time(s.lapTimeSec||0));const section=app.duel.course?.sectionAt?.(s.s)?.name||'COMPLETE BOTH LAPS';text('stage-objective',s.objective?.kind==='checkpointRush'?`GATES ${s.checkpointRush?.passed||0} / ${s.checkpointRush?.total||12} · EACH GATE +${s.checkpointRush?.extensionSec||0} SEC`:s.objective?.kind==='driftTrial'?`BANK ${credits(s.objective.targetScore)} POINTS · FINISH BOTH LAPS`:s.objective?.kind==='stuntTrial'?`LANDINGS ${s.jumps||0} / ${s.objective.targetJumps} · CRUSHES ${s.crushCount||0} / ${s.objective.targetCrushes} · ${time(Math.max(0,s.timeLimitSec-s.stageTimeSec-(s.racePenaltySec||0)))} LEFT`:`${section}${s.timeLimitSec?` · ESCAPE IN ${time(Math.max(0,s.timeLimitSec-s.stageTimeSec-(s.racePenaltySec||0)))}`:s.mode==='timetrial'&&s.parTimeSec?` · TARGET ${time(s.parTimeSec)}`:''}`);text('speed-value',String(Math.round(s.speedMph)).padStart(3,'0')); text('gear-value',s.gear+1); text('rpm-value',(clamp(s.revs)*8).toFixed(1));
  ui['rpm-fill'].style.transform=`scaleX(${clamp(s.revs)})`; ui['rpm-fill'].classList.toggle('redline',s.revs>DRIVE.redlineWarnFrac); ui['boost-fill'].style.transform=`scaleX(${clamp(s.boost??1)})`; ui.stage.classList.toggle('is-boosting',!!s.boosting); text('camera-label',`${(app.cameraMode||'chase').toUpperCase()} CAM`); text('style-score',String(s.score||0).padStart(4,'0')); text('combo-label',s.combo>1?`×${s.combo} COMBO`:'');
  const drift=s.objective?.kind==='driftTrial',rush=s.objective?.kind==='checkpointRush';ui['drift-panel'].hidden=!drift;ui['checkpoint-panel'].hidden=!rush;ui['style-score-panel'].hidden=drift||rush;
  if(rush){
    const gates=s.checkpointRush,notice=app.checkpointNotice,left=Math.max(0,s.timeLimitSec-s.stageTimeSec-(s.racePenaltySec||0));
    text('checkpoint-passed',`${gates.passed} / ${gates.total}`);text('checkpoint-time',time(left));ui['checkpoint-panel'].classList.toggle('time-low',left<10);ui['checkpoint-target-fill'].style.transform=`scaleX(${clamp(gates.passed/gates.total)})`;
    const physicalGates=app.duel.course.features.rushGates,next=physicalGates[gates.nextGate%physicalGates.length],distance=next?Math.max(0,Math.floor(gates.nextGate/physicalGates.length)*app.duel.course.length+next.s-s.s):0;
    text('checkpoint-next',gates.nextGate>=gates.total?'FINISH BOTH LAPS':`NEXT GATE ${gates.nextGate+1} / ${gates.total} · ${Math.ceil(distance)} M`);
    text('checkpoint-notice',notice&&notice.expiresAt>s.stageTimeSec?notice.type==='passed'?`Gate ${notice.index+1} passed · +${notice.extensionSec} seconds`:`Gate ${notice.index+1} missed · no time gained`:gates.missed?`${gates.missed} missed. Complete the run or try again.`:gates.nextGate>=gates.total?'All gates passed. Bring it home.':`Pass through the next lit gate for +${gates.extensionSec} seconds.`);
  }
  if(drift){
    const banked=Math.round(s.drift?.bankedScore||0),chain=Math.round(s.drift?.chainScore||0),target=s.objective.targetScore,notice=app.driftNotice;
    text('drift-banked',credits(banked));text('drift-target-label',`/ ${credits(target)}`);ui['drift-chain'].firstChild.textContent=`+${credits(chain)} `;text('drift-multiplier',`×${(s.drift?.multiplier||1).toFixed(2)}`);ui['drift-target-fill'].style.transform=`scaleX(${clamp(banked/target)})`;ui['drift-panel'].classList.toggle('target-met',banked>=target);
    const reason={hit:'collision',reset:'reset',offroad:'off-road',uncontrolled:'spin',reverse:'wrong way',airborne:'airborne',inactive:'run stopped',invalid:'recovery',unfinished:'run ended'};
    text('drift-notice',notice&&notice.expiresAt>s.stageTimeSec?notice.type==='banked'?`Banked +${credits(notice.points)}`:`Chain lost · ${reason[notice.reason]||'recovery'}`:banked>=target?'Target met. Finish both laps.':chain?'Straighten to bank. Avoid impacts and dirt.':'Slide above 45 MPH to build a chain.');
  }
  const length=app.duel.course?.raceLength||app.duel.course?.length||1,progress=clamp(s.s/length); text('route-percent',`${Math.floor(progress*100)}%`); text('route-remaining',`${(Math.max(0,length-s.s)/1000).toFixed(1)} KM TO GO`); ui['progress-fill'].style.transform=`scaleX(${progress})`;
  if(s.rival){
    const gap=s.rival.s-s.s, settled=s.status==='stage_result'||s.status==='complete';
    const behind=settled?s.results?.beatRival===false:s.rival.finished||gap>0;
    text('race-position',behind?'02':'01');
    text('gap-label',settled?'FINISH POSITION':s.rival.finished?'RIVAL FINISHED':behind?'RIVAL AHEAD':'RIVAL BEHIND');
    text('rival-gap',settled?(behind?'SECOND PLACE':'FIRST PLACE'):s.rival.finished?'KEEP PUSHING':`${(Math.abs(gap)/(Math.max(45,s.speedMph,s.rival.speedMph||0)*DRIVE.mphToWorld)).toFixed(1)} SEC`);
  }else{text('race-position',rush?'CP':s.objective?.kind==='driftTrial'?'DR':s.objective?'ST':s.timeLimitSec?'GO':'TT');text('gap-label',rush?'CHECKPOINT CLOCK':s.objective?.kind==='driftTrial'?'DRIFT DEADLINE':s.objective?'STUNT DEADLINE':s.timeLimitSec?'ESCAPE THE PURSUIT':app.ghostRecord?(app.ghostEnabled?'BEST GHOST':'BEST GHOST OFF'):'RACE THE CLOCK');text('rival-gap',s.objective?time(Math.max(0,s.timeLimitSec-s.stageTimeSec-(s.racePenaltySec||0))):s.timeLimitSec?'BEAT THE DEADLINE':app.ghostRecord?time(app.ghostRecord.timeSec):'RECORD YOUR GHOST');} ui['position-total'].hidden=!s.rival; ui['rival-legend'].hidden=!s.rival;
  const hits=s.majorCrashes||0,persistent=!!app.duel.stageDef.persistentVehicle;ui['lives-display'].hidden=persistent;
  if(ui['lives-display'].dataset.value!==String(hits)){ui['lives-display'].dataset.value=hits;ui['lives-display'].innerHTML=Array.from({length:DRIVE.majorCrashLimit},(_,i)=>`<i class="${i<DRIVE.majorCrashLimit-hits?'healthy':''}"></i>`).join('');ui['lives-display'].setAttribute('aria-label',`${hits} of ${DRIVE.majorCrashLimit} major crashes`);}
  text('damage-label',persistent?`IMPACTS ADD +${app.duel.stageDef.chaseCrashPenaltySec||8} SEC`:hits===DRIVE.majorCrashLimit-1?'CRITICAL · NEXT MAJOR CRASH IS FATAL':`${hits} / ${DRIVE.majorCrashLimit} MAJOR CRASHES`);ui['damage-label'].classList.toggle('critical',!persistent&&hits>=DRIVE.majorCrashLimit-1);
  const objectiveTrial=!!s.objective;ui['radar-label'].hidden=objectiveTrial;ui['radar-meter'].hidden=objectiveTrial;
  const p=s.police; text('radar-label',p.pursuit?.active?'PURSUIT / OUTRUN THE PATROL':p.beep>.2?'RADAR / SPEED TRAP AHEAD':'RADAR CLEAR'); ui['radar-label'].classList.toggle('warning',p.beep>.2||!!p.pursuit?.active); ui['radar-fill'].style.transform=`scaleX(${p.pursuit?.active?1:clamp(p.beep)})`;
  if(s.status==='countdown'){text('countdown-number',Math.max(1,Math.ceil(s.countdown)));text('countdown-word',s.countdown>1?'GET READY':'MAKE IT COUNT');}
  const crash=s.crashFlash>0||s.impactTimer>0; ui['crash-flash'].hidden=!crash;
  const dirtCourse=!!app.duel.stageDef.offroad||!!app.duel.stageDef.arena;
  const callout=crash?(s.catastrophic?'CATASTROPHIC IMPACT':s.lastCrashReason==='engine_blew'?'ENGINE BLOWN':s.lastCrashReason==='rock'?'ROCK IMPACT':'COLLISION'):s.calloutTimer>0?s.callout:s.boundaryWarning?'RETURN TO THE ROUTE':s.preparedGravel?'GRAVEL TRACK':s.offRoad?'LOOSE SURFACE':s.drifting?'DRIFT':'';
  ui['race-callout'].hidden=!callout||!!s.paused; text('callout-kicker',s.catastrophic?'FIVE HITS. END OF THE ROAD.':crash?persistent?'THE CAR SURVIVES. THE CLOCK KEEPS RUNNING.':hits===DRIVE.majorCrashLimit-1?'CHASSIS CRITICAL. MAKE THIS LIFE COUNT.':'SHAKE IT OFF. KEEP DRIVING.':s.boundaryWarning?'COURSE BOUNDARY · RESET AHEAD':s.preparedGravel?'KEEP YOUR LINE':s.offRoad?dirtCourse?'CONTROL THE SLIDE':'FIND THE TARMAC':s.boosting?'FULL SEND':'MAKE EVERY MOVE COUNT');text('callout-text',callout);ui['race-callout'].classList.toggle('crash-callout',crash);
  ui.stage.classList.toggle('is-arena',!!app.duel.stageDef.arena);ui['arena-crush'].hidden=!app.duel.stageDef.arena;text('arena-crush',`CRUSHED ${Math.max(0,Math.min(6,Math.floor(s.crushCount||0)))} / 6`);
  text('route-section',section);text('route-lap',`${s.currentLap||s.lap||1} / ${app.duel.stageDef.laps||2}`);ui['police-legend'].hidden=!s.police?.pursuit?.active;ui['shortcut-legend'].hidden=!app.duel.course?.features.shortcuts.length;ui['shortcut-b-legend'].hidden=(app.duel.course?.features.shortcuts.length||0)<2;routeMap.update(app.duel.course,s);
}

document.addEventListener('keydown',e=>{if(e.code==='Escape'&&(garageOpen||playersOpen||leaderboardOpen)){e.preventDefault();garageOpen=playersOpen=leaderboardOpen=false;lastScreen=null;updateMenuCar();renderState(app.duel.state);return;}if(e.code!=='Tab'||ui['modal-layer'].hidden)return;const buttons=[...ui['modal-layer'].querySelectorAll('button:not(:disabled),select,input,summary')],first=buttons[0],last=buttons.at(-1);if(!first)return;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}},{signal:domEvents.signal});
app.onFrame=renderState;updatePlayers();updateMenuCar();updateMenuScene();renderState(app.duel.state);ensureRenderer();app.start();
